### ISSUE TITLE
where should I ping you to get the link?

### ISSUE THREAD

**Issue by darkmonk94** [VIJAYBORATE1999/BBL-Loan-Origination#1]

**Comment by darkmonk94** [comment]
I am Aaron from Jain University and currently doing a project for my final year related to Banking system so thought this project code will help me. I will not copy your project sir, I will try to understand the code and replicate something similar

**Comment by VIJAYBORATE1999** [comment]
Sure Most welcome 🤗 Give your WhatsApp No will send you over that !

Work Hard All the best Dude !

**Comment by darkmonk94** [comment]
On Independence Day, my phone fell down during bike ride and display gone so I give it in service station for repair. Sorry for that.
Could you sent it over a email? my email id- aarondarkmonk94@gmail.com

**Comment by darkmonk94** [comment]
or could you sent it to my friends whatsapp number- 7627842989

**Comment by VIJAYBORATE1999** [comment]
Parcel 📦 Milaaa 😂 ? Nice try ! Harsh  Beta 🤗

Tell Pico PJ I got Shortlisted at IBM by This Java Project 😁

**Comment by VIJAYBORATE1999** [comment]
### 1. **Ache Say  Home-Work Karrke ayya karoo Beta😂**

**Comment by VIJAYBORATE1999** [comment]
😂Gaaand Fatt gayyi Harsh ki ?
Harsh ki Maa ki Chut me Mera Land

**Comment by VIJAYBORATE1999** [comment]
😂Closing this issue (Pico)
